### ISSUE TITLE
Checklist before publishing svelte version

### ISSUE THREAD

**Issue by Gregable** [Gregable/social-security-tools#235]
I'm in progress rewriting the site using typescript and svelte. This issue will keep track of any sub-tasks that need attention before I make the swap:

- [ ] Verify the tablet and mobile width versions
- [ ] Verify the print version
- [ ] Ensure that the sidebar is tracking scrolling correctly
- [ ] Ensure that the future earnings sliders stick in the correct area of the UI
